name: fiction_reader
description: Fiction reader

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  http: ^0.12.2

  html: ^0.14.0+4

  draggable_scrollbar: ^0.0.4

  provider: ^4.3.2+2

  sqflite: 1.3.1+2

  google_fonts: ^1.1.1

  shared_preferences: ^0.5.12+2

dev_dependencies:
  test: ^1.15.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Courgette
      fonts:
        - asset: assets/fonts/Courgette/Courgette-Regular.ttf
    - family: Liu_Jian_Mao_Cao
      fonts:
        - asset: assets/fonts/Liu_Jian_Mao_Cao/LiuJianMaoCao-Regular.ttf
    - family: LongCang
      fonts:
        - asset: assets/fonts/Long_Cang/LongCang-Regular.ttf
    - family: Ma_Shan_Zheng
      fonts:
        - asset: assets/fonts/Ma_Shan_Zheng/MaShanZheng-Regular.ttf
    - family: Noto_Serif_SC
      fonts:
        - asset: assets/fonts/Noto_Serif_SC/NotoSerifSC-Black.otf
        - asset: assets/fonts/Noto_Serif_SC/NotoSerifSC-Bold.otf
        - asset: assets/fonts/Noto_Serif_SC/NotoSerifSC-ExtraLight.otf
        - asset: assets/fonts/Noto_Serif_SC/NotoSerifSC-Light.otf
        - asset: assets/fonts/Noto_Serif_SC/NotoSerifSC-Medium.otf
        - asset: assets/fonts/Noto_Serif_SC/NotoSerifSC-Regular.otf
        - asset: assets/fonts/Noto_Serif_SC/NotoSerifSC-SemiBold.otf
    - family: ZCOOL_KuaiLe
      fonts:
        - asset: assets/fonts/ZCOOL_KuaiLe/ZCOOLKuaiLe-Regular.ttf
  #        - asset: assets/fonts/Courgette-Regular.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
